"""empty message

Revision ID: 527936ce8e06
Revises: None
Create Date: 2015-06-02 21:59:58.056705

"""

# revision identifiers, used by Alembic.
revision = '527936ce8e06'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
